---
- name: Update pacman cache.
  community.general.pacman:
    update_cache: true
  become: true

- name: Install dependencies.
  ansible.builtin.package:
    name:
      - git
      - base-devel
    state: present
  become: true
